name: PyInstaller Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Install PyInstaller
    - name: Install PyInstaller
      run: pip install pyinstaller

    # Build the application
    - name: Build executable
      run: |
        pyinstaller --onefile your_script.py
        ls dist/

    # Upload built artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: application-executable
        path: dist/
